language: java

sudo: false # faster builds

jdk:
  - openjdk8
  - openjdk11
  - oraclejdk11

script:
  - mvn clean verify -P run-its

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
