language: java

sudo: false # faster builds

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

script:
  - mvn clean verify -P run-its

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
